baseURL: "https://arnolfokam.github.io" 
title: Arnol Fokam
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2
        - name: Data
          url: data/
          weight: 3 
        - name: Newsletter
          url: https://pmichaillat.substack.com
          weight: 4

params:
    description: "I am an MSc by dissertation student in Computer Science at the University of the Witwatersrand. I am also a part-time engineering intern at Instadeep."
    author: Arnol Fokam
    googleAnalyticsID: "G-4EJRYDQ3SZ"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Arnol Fokam
          subtitle: "
          <div class='profile_desc'>
            <p>
              I am an MSc by dissertation student in Computer Science at the University of the Witwatersrand where I received the <b><a href='https://deepmind.google/about/education/' target='_blank'>DeepMind Scholarship</a></b> 
              to support my studies in Artificial Intelligence. My research focuses on the development of novel data augmentation techniques for 
              <b><a href='https://ankeshanand.com/blog/2020/01/26/contrative-self-supervised-learning.html' target='_blank'>contrastive self-supervised learning</a></b>.
            </p>
            <br/>
            <p>
              Additionally, I am a part-time engineering intern at Instadeep, where I work on 
              <b><a href='https://quality-diversity.github.io/' target='_blank'>quality diversity</a></b> to generate training data to help a 
              reinforcement learning agent perform 3D bin packing.
            </p>
          </div>
          "
          imageUrl: "profile.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Arnol Fokam
          buttons:
            - name: Publications
              url: publications/
            # - name: Posts
            #   url: posts/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
    socialIcons:
        - name: Resume
          url: resume.pdf
        - name: Email
          url: mailto:a.fokam@instadeep.com
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cA1hu0UAAAAJ&hl=en
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/ArnolFokam
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        - name: Twitter
          url: https://twitter.com/ArnolFokam
        - name: LinkedIn
          url: https://www.linkedin.com/in/arnolfokam

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Arnol Fokam"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
